# Server configuration
server:
  port: ${port:9090}

# Spring and datasource configuration
spring:
  datasource:
    url: jdbc:${repoadmin_db_jdbc:postgresql}://${repoadmin_db_host:localhost}:${repoadmin_db_port:5432}/${repoadmin_db_database:repomgr}
    username: ${repoadmin_db_username:repomgr}
    password: ${repoadmin_db_password:repomgr}
    driver-class-name: ${repoadmin_db_driver:org.postgresql.Driver}
    tomcat:
      connection-properties: stringtype=unspecified
  jpa:
    open-in-view: false
    properties:
      hibernate:
        show_sql: false
        format_sql: true
        temp:
          use_jdbc_metadata_defaults: false
security:
  jwt:
    client-secret: secret

# Actuator information
info:
  app:
    name: RepositoryAdmin
    version: 0.3.0
    description: Repository Administration

# Logging
logging:
  level:
    org:
      hibernate:
        type: error

# RepoManager configuration
repomanager:
  security:
    signingKey: secret
    tokenExpirationTime: 3600

